// Code generated by goctl. DO NOT EDIT.
package types

type CreateUserReq struct {
	Username string `json:"username"`          // 用户名
	NickName string `json:"nickname,optional"` // 用户别名
	Password string `json:"password"`          // 密码
	Roles    string `json:"roles"`             // 用户角色列表
}

type CreateUserResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type GetUserReq struct {
	Username string `json:"username,optional"` // 用户名
	UUID     string `json:"uuid,optional"`     // 用户uuid
}

type UserInfo struct {
	UUID      string `json:"uuid"`              // 用户uuid
	Username  string `json:"username"`          // 用户名
	NickName  string `json:"nickname,optional"` // 用户别名
	Roles     string `json:"rolse"`             // 用户角色列表
	LockAt    string `json:"lockat,optional"`   // 用户锁定时间
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type GetUserResp struct {
	Code    int        `json:"code"`
	Message string     `json:"message"`
	Data    []UserInfo `json:"data"`
}

type DeleteUserReq struct {
	UUID     string `json:"uuid"`     // 用户uuid
	Username string `json:"username"` // 用户名
}

type DeleteUserResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type LoginReq struct {
	Username string `json:"username"` //用户名
	Password string `json:"password"` //密码
}

type TokenInfo struct {
	Token string `json:"token"` // token
}

type LoginResq struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    TokenInfo `json:"data"`
}
