// Code generated by goctl. DO NOT EDIT.
package types

type CreateUserReq struct {
	Username string `json:"username"`           // 用户名
	NickName string `json:"nickname,omitempty"` // 用户别名
	Password string `json:"password"`           // 密码
	Roles    uint   `json:"roles"`              // 用户角色列表
}

type CreateUserResp struct {
	Message string `json:"message"`
}

type GetUserReq struct {
	Username string `path:"username"` // 用户名
}

type GetUserResp struct {
	UUID      string `json:"uuid"`               // 用户uuid
	Username  string `json:"username"`           // 用户名
	NickName  string `json:"nickname,omitempty"` // 用户别名
	Password  string `json:"password"`           // 密码
	Roles     uint   `json:"rolse"`              // 用户角色列表
	LockAt    string `json:"lockat,omitempty"`   // 用户锁定时间
	ID        uint   `json:"id"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
